Appman-876 Initial setup to start the import of the data
SkillsFundingAgency/das-referencedata-jobs pull request #2
Opened 2024-04-03 12:34 UTC by Pauljgraham

2024-04-09 09:54 UTC, cofaulco requested changes

2024-04-09 09:54 UTC, cofaulco commented on src/SFA.DAS.ReferenceData.Jobs/readme.md
can we add a proper readme for the application please?

2024-04-09 09:54 UTC, cofaulco commented on src/SFA.DAS.ReferenceData.Jobs/Interfaces/IApimClient.cs
> +    public interface IApimClient
I believe in other solutions we refer to 'OuterApi' as opposed to APIM. Could we maintain the consistency there?

2024-04-29 19:27 UTC, cofaulco requested changes

2024-04-29 19:27 UTC, cofaulco commented on README.md
> +A NServiceBus timer periodically starts the import process, this import process calls the outer API which in turn fetches the external data and populates it in the appropriate databases.
the timer trigger is not NServicebus related

2024-04-29 19:27 UTC, cofaulco commented on README.md
> +* NServiceBus
don't think we have anything NServicebus related

2024-04-29 19:27 UTC, cofaulco commented on README.md
> +* .Net 6.0
Net 8.0?

2024-04-29 19:27 UTC, cofaulco commented on src/SFA.DAS.ReferenceData.Jobs/SFA.DAS.ReferenceData.Jobs.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
do we need to explicitly make sure this isn't copied to the publish directory?

2024-04-29 19:27 UTC, cofaulco commented on src/SFA.DAS.ReferenceData.Jobs/readme.md
> +# TimerTrigger - C<span>#</span>
second Readme?

2024-04-30 09:48 UTC, Pauljgraham commented on README.md
> +A NServiceBus timer periodically starts the import process, this import process calls the outer API which in turn fetches the external data and populates it in the appropriate databases.
I'm always amazed, how stupid I can be at times. Of course it's not related to NSB,

2024-04-30 09:51 UTC, Pauljgraham commented on README.md
> +* .Net 6.0
working for too long on .NET 6 upgrades

2024-04-30 09:54 UTC, Pauljgraham commented on src/SFA.DAS.ReferenceData.Jobs/SFA.DAS.ReferenceData.Jobs.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
No, quite the opposite

2024-04-30 09:54 UTC, Pauljgraham commented on src/SFA.DAS.ReferenceData.Jobs/readme.md
> +# TimerTrigger - C<span>#</span>
deleted

2024-04-30 13:36 UTC, cofaulco approved these changes

2024-06-11 08:54 UTC, merged